server:
  port: 9001
spring:
  application:
    name: ocean-auth
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: @profiles.active@
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
  config:
    import:
      - optional:nacos:application-@profiles.active@.yml
      - optional:nacos:${spring.application.name}-@profiles.active@.yml
  redis:
    host: localhost:3306